CREATE DATABASE ERP;
use ERP;

CREATE TABLE IF NOT EXISTS Clientes(
ID_Cliente INT UNSIGNED AUTO_INCREMENT NOT NULL,
Nome VARCHAR (100),
Numero INT,
Email VARCHAR (100)
);

CREATE TABLE IF NOT EXISTS Serviços(
ID_Serviços INT UNSIGNED AUTO_INCREMENT NOT NULL,
Nome_Serviços VARCHAR (100)
);

CREATE TABLE IF NOT EXISTS Financeiro(
Valores double
);

CREATE TABLE IF NOT EXISTS Rh(
ID_Funcionarios INT UNSIGNED AUTO_INCREMENT NOT NULL,
Nome_funcionarios VARCHAR (100)
);

CREATE TABLE IF NOT EXISTS Estoque(
ID_Produtos INT UNSIGNED AUTO_INCREMENT NOT NULL,
Nome_Produtos VARCHAR (100)
);

CREATE TABLE IF NOT EXISTS Agendamentos(
Agendamentos DATE
);

